version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Shanghai"
    target-branch: "master"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
    labels:
      - "dependencies"
      - "java"
    groups:
      maven-minor-and-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]
      maven-major:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["major"]

  - package-ecosystem: "maven"
    directory: "/plugins/eclipse"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Shanghai"
    target-branch: "master"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "build(deps-eclipse)"
    labels:
      - "dependencies"
      - "java"
      - "eclipse"
    groups:
      eclipse-minor-and-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]
      eclipse-major:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["major"]

  - package-ecosystem: "gradle"
    directory: "/plugins/intellij"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Shanghai"
    target-branch: "master"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "build(deps-intellij)"
    labels:
      - "dependencies"
      - "intellij"
    groups:
      intellij-minor-and-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]
      intellij-major:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Shanghai"
    target-branch: "master"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        applies-to: version-updates
        patterns: ["*"]
