name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ ubuntu-latest , windows-latest , macos-latest ]
        java: [ 11 ]
        experimental: [ false ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt
      - name: Build
        run: |
          mvn clean install -DskipTests
      - name: Build eclipse plugin
        run: |
          cd ./plugins/eclipse
          mvn clean install -DskipTests
      - name: Build intellij plugin
        run: |
          cd ./plugins/intellij
          chmod 777 ./gradlew
          ./gradlew buildPlugin -s
